name = "FunctionalStateMachine"
uuid = "3e9e306e-7e3c-11e9-12d2-8f8f67a2f951"
keywords = ["state machine"]
desc = "Functional state machine with stepping and visualization tools."
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
DocStringExtensions = "≥ 0.7"
ProgressMeter = "≥ 0.6"
Requires = "≥ 0.5.2"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
